# coding: utf-8

"""
    Data API

    Serves the Clever Data API  # noqa: E501

    OpenAPI spec version: 3.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import clever3
from clever3.models.resource_response import ResourceResponse  # noqa: E501
from clever3.rest import ApiException


class TestResourceResponse(unittest.TestCase):
    """ResourceResponse unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testResourceResponse(self):
        """Test ResourceResponse"""
        # FIXME: construct object with mandatory attributes with example values
        # model = clever3.models.resource_response.ResourceResponse()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
