# coding: utf-8

"""
    Data API

    Serves the Clever Data API  # noqa: E501

    OpenAPI spec version: 3.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import clever
from clever.models.term_response import TermResponse  # noqa: E501
from clever.rest import ApiException


class TestTermResponse(unittest.TestCase):
    """TermResponse unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testTermResponse(self):
        """Test TermResponse"""
        # FIXME: construct object with mandatory attributes with example values
        # model = clever.models.term_response.TermResponse()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
