# coding: utf-8

"""
    Data API

    Serves the Clever Data API  # noqa: E501

    OpenAPI spec version: 3.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import clever
from clever.models.terms_response import TermsResponse  # noqa: E501
from clever.rest import ApiException


class TestTermsResponse(unittest.TestCase):
    """TermsResponse unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testTermsResponse(self):
        """Test TermsResponse"""
        # FIXME: construct object with mandatory attributes with example values
        # model = clever.models.terms_response.TermsResponse()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
