# coding: utf-8

"""
    Data API

    Serves the Clever Data API  # noqa: E501

    OpenAPI spec version: 3.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import clever
from clever.models.section_response import SectionResponse  # noqa: E501
from clever.rest import ApiException


class TestSectionResponse(unittest.TestCase):
    """SectionResponse unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testSectionResponse(self):
        """Test SectionResponse"""
        # FIXME: construct object with mandatory attributes with example values
        # model = clever.models.section_response.SectionResponse()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
