# coding: utf-8

"""
    Data API

    Serves the Clever Data API  # noqa: E501

    OpenAPI spec version: 3.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import clever3
from clever3.models.district_contact import DistrictContact  # noqa: E501
from clever3.rest import ApiException


class TestDistrictContact(unittest.TestCase):
    """DistrictContact unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testDistrictContact(self):
        """Test DistrictContact"""
        # FIXME: construct object with mandatory attributes with example values
        # model = clever3.models.district_contact.DistrictContact()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
