# coding: utf-8

"""
    Data API

    Serves the Clever Data API  # noqa: E501

    OpenAPI spec version: 3.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import clever3
from clever3.models.course_response import CourseResponse  # noqa: E501
from clever3.rest import ApiException


class TestCourseResponse(unittest.TestCase):
    """CourseResponse unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testCourseResponse(self):
        """Test CourseResponse"""
        # FIXME: construct object with mandatory attributes with example values
        # model = clever3.models.course_response.CourseResponse()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
