# coding: utf-8

"""
    Data API

    Serves the Clever Data API  # noqa: E501

    OpenAPI spec version: 3.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import clever
from clever.api.courses_api import CoursesApi  # noqa: E501
from clever.rest import ApiException


class TestCoursesApi(unittest.TestCase):
    """CoursesApi unit test stubs"""

    def setUp(self):
        self.api = CoursesApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_get_course(self):
        """Test case for get_course

        """
        pass

    def test_get_courses(self):
        """Test case for get_courses

        """
        pass

    def test_get_district_for_course(self):
        """Test case for get_district_for_course

        """
        pass

    def test_get_resources_for_course(self):
        """Test case for get_resources_for_course

        """
        pass

    def test_get_schools_for_course(self):
        """Test case for get_schools_for_course

        """
        pass

    def test_get_sections_for_course(self):
        """Test case for get_sections_for_course

        """
        pass


if __name__ == '__main__':
    unittest.main()
