# coding: utf-8

"""
    Data API

    Serves the Clever Data API  # noqa: E501

    OpenAPI spec version: 3.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import clever3
from clever3.models.school_enrollment import SchoolEnrollment  # noqa: E501
from clever3.rest import ApiException


class TestSchoolEnrollment(unittest.TestCase):
    """SchoolEnrollment unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testSchoolEnrollment(self):
        """Test SchoolEnrollment"""
        # FIXME: construct object with mandatory attributes with example values
        # model = clever3.models.school_enrollment.SchoolEnrollment()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
