# coding: utf-8

# flake8: noqa
"""
    Data API

    Serves the Clever Data API  # noqa: E501

    OpenAPI spec version: 2.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

# import models into model package
from clever.models.admin_name import AdminName
from clever.models.bad_request import BadRequest
from clever.models.contact import Contact
from clever.models.contact_response import ContactResponse
from clever.models.contacts_response import ContactsResponse
from clever.models.course import Course
from clever.models.course_response import CourseResponse
from clever.models.courses_response import CoursesResponse
from clever.models.credentials import Credentials
from clever.models.district import District
from clever.models.district_admin import DistrictAdmin
from clever.models.district_admin_response import DistrictAdminResponse
from clever.models.district_admins_response import DistrictAdminsResponse
from clever.models.district_response import DistrictResponse
from clever.models.districts_response import DistrictsResponse
from clever.models.internal_error import InternalError
from clever.models.link import Link
from clever.models.location import Location
from clever.models.name import Name
from clever.models.not_found import NotFound
from clever.models.principal import Principal
from clever.models.school import School
from clever.models.school_admin import SchoolAdmin
from clever.models.school_admin_response import SchoolAdminResponse
from clever.models.school_admins_response import SchoolAdminsResponse
from clever.models.school_response import SchoolResponse
from clever.models.schools_response import SchoolsResponse
from clever.models.section import Section
from clever.models.section_response import SectionResponse
from clever.models.sections_response import SectionsResponse
from clever.models.student import Student
from clever.models.student_response import StudentResponse
from clever.models.students_response import StudentsResponse
from clever.models.teacher import Teacher
from clever.models.teacher_response import TeacherResponse
from clever.models.teachers_response import TeachersResponse
from clever.models.term import Term
from clever.models.term_response import TermResponse
from clever.models.terms_response import TermsResponse
