# coding: utf-8

"""
    Data API

    Serves the Clever Data API  # noqa: E501

    OpenAPI spec version: 2.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import clever
from clever.models.district_response import DistrictResponse  # noqa: E501
from clever.rest import ApiException


class TestDistrictResponse(unittest.TestCase):
    """DistrictResponse unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testDistrictResponse(self):
        """Test DistrictResponse"""
        # FIXME: construct object with mandatory attributes with example values
        # model = clever.models.district_response.DistrictResponse()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
