# coding: utf-8

"""
    Data API

    Serves the Clever Data API  # noqa: E501

    OpenAPI spec version: 2.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import clever
from clever.api.district_admins_api import DistrictAdminsApi  # noqa: E501
from clever.rest import ApiException


class TestDistrictAdminsApi(unittest.TestCase):
    """DistrictAdminsApi unit test stubs"""

    def setUp(self):
        self.api = DistrictAdminsApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_get_district_admin(self):
        """Test case for get_district_admin

        """
        pass

    def test_get_district_admins(self):
        """Test case for get_district_admins

        """
        pass

    def test_get_district_for_district_admin(self):
        """Test case for get_district_for_district_admin

        """
        pass


if __name__ == '__main__':
    unittest.main()
