# coding: utf-8

"""
    Data API

    Serves the Clever Data API  # noqa: E501

    OpenAPI spec version: 2.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import clever
from clever.api.schools_api import SchoolsApi  # noqa: E501
from clever.rest import ApiException


class TestSchoolsApi(unittest.TestCase):
    """SchoolsApi unit test stubs"""

    def setUp(self):
        self.api = SchoolsApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_get_district_for_school(self):
        """Test case for get_district_for_school

        """
        pass

    def test_get_school(self):
        """Test case for get_school

        """
        pass

    def test_get_schools(self):
        """Test case for get_schools

        """
        pass

    def test_get_sections_for_school(self):
        """Test case for get_sections_for_school

        """
        pass

    def test_get_students_for_school(self):
        """Test case for get_students_for_school

        """
        pass

    def test_get_teachers_for_school(self):
        """Test case for get_teachers_for_school

        """
        pass


if __name__ == '__main__':
    unittest.main()
