# coding: utf-8

"""
    Data API

    Serves the Clever Data API  # noqa: E501

    OpenAPI spec version: 2.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import clever
from clever.models.school_admins_response import SchoolAdminsResponse  # noqa: E501
from clever.rest import ApiException


class TestSchoolAdminsResponse(unittest.TestCase):
    """SchoolAdminsResponse unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testSchoolAdminsResponse(self):
        """Test SchoolAdminsResponse"""
        # FIXME: construct object with mandatory attributes with example values
        # model = clever.models.school_admins_response.SchoolAdminsResponse()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
