# coding: utf-8

"""
    Data API

    Serves the Clever Data API  # noqa: E501

    OpenAPI spec version: 2.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import clever
from clever.api.teachers_api import TeachersApi  # noqa: E501
from clever.rest import ApiException


class TestTeachersApi(unittest.TestCase):
    """TeachersApi unit test stubs"""

    def setUp(self):
        self.api = TeachersApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_get_district_for_teacher(self):
        """Test case for get_district_for_teacher

        """
        pass

    def test_get_school_for_teacher(self):
        """Test case for get_school_for_teacher

        """
        pass

    def test_get_schools_for_teacher(self):
        """Test case for get_schools_for_teacher

        """
        pass

    def test_get_sections_for_teacher(self):
        """Test case for get_sections_for_teacher

        """
        pass

    def test_get_students_for_teacher(self):
        """Test case for get_students_for_teacher

        """
        pass

    def test_get_teacher(self):
        """Test case for get_teacher

        """
        pass

    def test_get_teachers(self):
        """Test case for get_teachers

        """
        pass


if __name__ == '__main__':
    unittest.main()
