# coding: utf-8

"""
    Data API

    Serves the Clever Data API  # noqa: E501

    OpenAPI spec version: 2.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import clever
from clever.models.schools_response import SchoolsResponse  # noqa: E501
from clever.rest import ApiException


class TestSchoolsResponse(unittest.TestCase):
    """SchoolsResponse unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testSchoolsResponse(self):
        """Test SchoolsResponse"""
        # FIXME: construct object with mandatory attributes with example values
        # model = clever.models.schools_response.SchoolsResponse()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
