# coding: utf-8

"""
    Data API

    Serves the Clever Data API  # noqa: E501

    OpenAPI spec version: 2.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import clever
from clever.api.contacts_api import ContactsApi  # noqa: E501
from clever.rest import ApiException


class TestContactsApi(unittest.TestCase):
    """ContactsApi unit test stubs"""

    def setUp(self):
        self.api = ContactsApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_get_contact(self):
        """Test case for get_contact

        """
        pass

    def test_get_contacts(self):
        """Test case for get_contacts

        """
        pass

    def test_get_district_for_contact(self):
        """Test case for get_district_for_contact

        """
        pass

    def test_get_students_for_contact(self):
        """Test case for get_students_for_contact

        """
        pass


if __name__ == '__main__':
    unittest.main()
