# coding: utf-8

"""
    Data API

    Serves the Clever Data API  # noqa: E501

    OpenAPI spec version: 2.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import clever
from clever.api.school_admins_api import SchoolAdminsApi  # noqa: E501
from clever.rest import ApiException


class TestSchoolAdminsApi(unittest.TestCase):
    """SchoolAdminsApi unit test stubs"""

    def setUp(self):
        self.api = SchoolAdminsApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_get_district_for_school_admin(self):
        """Test case for get_district_for_school_admin

        """
        pass

    def test_get_school_admin(self):
        """Test case for get_school_admin

        """
        pass

    def test_get_school_admins(self):
        """Test case for get_school_admins

        """
        pass

    def test_get_schools_for_school_admin(self):
        """Test case for get_schools_for_school_admin

        """
        pass


if __name__ == '__main__':
    unittest.main()
