# coding: utf-8

"""
    Data API

    Serves the Clever Data API  # noqa: E501

    OpenAPI spec version: 2.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import clever
from clever.api.students_api import StudentsApi  # noqa: E501
from clever.rest import ApiException


class TestStudentsApi(unittest.TestCase):
    """StudentsApi unit test stubs"""

    def setUp(self):
        self.api = StudentsApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_get_contacts_for_student(self):
        """Test case for get_contacts_for_student

        """
        pass

    def test_get_district_for_student(self):
        """Test case for get_district_for_student

        """
        pass

    def test_get_school_for_student(self):
        """Test case for get_school_for_student

        """
        pass

    def test_get_schools_for_student(self):
        """Test case for get_schools_for_student

        """
        pass

    def test_get_sections_for_student(self):
        """Test case for get_sections_for_student

        """
        pass

    def test_get_student(self):
        """Test case for get_student

        """
        pass

    def test_get_students(self):
        """Test case for get_students

        """
        pass

    def test_get_teachers_for_student(self):
        """Test case for get_teachers_for_student

        """
        pass


if __name__ == '__main__':
    unittest.main()
