# coding: utf-8

"""
    Data API

    Serves the Clever Data API  # noqa: E501

    OpenAPI spec version: 2.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import clever
from clever.models.admin_name import AdminName  # noqa: E501
from clever.rest import ApiException


class TestAdminName(unittest.TestCase):
    """AdminName unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testAdminName(self):
        """Test AdminName"""
        # FIXME: construct object with mandatory attributes with example values
        # model = clever.models.admin_name.AdminName()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
