# coding: utf-8

# flake8: noqa

"""
    Data API

    Serves the Clever Data API  # noqa: E501

    OpenAPI spec version: 3.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

# import apis into sdk package
from clever3.api.courses_api import CoursesApi
from clever3.api.districts_api import DistrictsApi
from clever3.api.resources_api import ResourcesApi
from clever3.api.schools_api import SchoolsApi
from clever3.api.sections_api import SectionsApi
from clever3.api.terms_api import TermsApi
from clever3.api.users_api import UsersApi
# import ApiClient
from clever3.api_client import ApiClient
from clever3.configuration import Configuration
# import models into sdk package
from clever3.models.bad_request import BadRequest
from clever3.models.contact import Contact
from clever3.models.course import Course
from clever3.models.course_response import CourseResponse
from clever3.models.courses_response import CoursesResponse
from clever3.models.credentials import Credentials
from clever3.models.district import District
from clever3.models.district_admin import DistrictAdmin
from clever3.models.district_contact import DistrictContact
from clever3.models.district_response import DistrictResponse
from clever3.models.districts_response import DistrictsResponse
from clever3.models.internal_error import InternalError
from clever3.models.link import Link
from clever3.models.location import Location
from clever3.models.name import Name
from clever3.models.not_found import NotFound
from clever3.models.principal import Principal
from clever3.models.resource import Resource
from clever3.models.resource_response import ResourceResponse
from clever3.models.resources_response import ResourcesResponse
from clever3.models.roles import Roles
from clever3.models.school import School
from clever3.models.school_enrollment import SchoolEnrollment
from clever3.models.school_response import SchoolResponse
from clever3.models.schools_response import SchoolsResponse
from clever3.models.section import Section
from clever3.models.section_response import SectionResponse
from clever3.models.sections_response import SectionsResponse
from clever3.models.staff import Staff
from clever3.models.student import Student
from clever3.models.student_relationship import StudentRelationship
from clever3.models.teacher import Teacher
from clever3.models.term import Term
from clever3.models.term_response import TermResponse
from clever3.models.terms_response import TermsResponse
from clever3.models.user import User
from clever3.models.user_response import UserResponse
from clever3.models.users_response import UsersResponse
