# coding: utf-8

# flake8: noqa

"""
    Data API

    Serves the Clever Data API  # noqa: E501

    OpenAPI spec version: 3.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

# import apis into sdk package
from clever.api.courses_api import CoursesApi
from clever.api.districts_api import DistrictsApi
from clever.api.resources_api import ResourcesApi
from clever.api.schools_api import SchoolsApi
from clever.api.sections_api import SectionsApi
from clever.api.terms_api import TermsApi
from clever.api.users_api import UsersApi
# import ApiClient
from clever.api_client import ApiClient
from clever.configuration import Configuration
# import models into sdk package
from clever.models.bad_request import BadRequest
from clever.models.contact import Contact
from clever.models.course import Course
from clever.models.course_response import CourseResponse
from clever.models.courses_response import CoursesResponse
from clever.models.credentials import Credentials
from clever.models.district import District
from clever.models.district_admin import DistrictAdmin
from clever.models.district_response import DistrictResponse
from clever.models.districts_response import DistrictsResponse
from clever.models.internal_error import InternalError
from clever.models.link import Link
from clever.models.location import Location
from clever.models.name import Name
from clever.models.not_found import NotFound
from clever.models.principal import Principal
from clever.models.resource import Resource
from clever.models.resource_response import ResourceResponse
from clever.models.resources_response import ResourcesResponse
from clever.models.roles import Roles
from clever.models.school import School
from clever.models.school_enrollment import SchoolEnrollment
from clever.models.school_response import SchoolResponse
from clever.models.schools_response import SchoolsResponse
from clever.models.section import Section
from clever.models.section_response import SectionResponse
from clever.models.sections_response import SectionsResponse
from clever.models.staff import Staff
from clever.models.student import Student
from clever.models.student_relationship import StudentRelationship
from clever.models.teacher import Teacher
from clever.models.term import Term
from clever.models.term_response import TermResponse
from clever.models.terms_response import TermsResponse
from clever.models.user import User
from clever.models.user_response import UserResponse
from clever.models.users_response import UsersResponse
